# # yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# language: "en-US"
# early_access: false
# reviews:
#   profile: "chill"
#   request_changes_workflow: false
#   high_level_summary: true
#   poem: true
#   review_status: true
#   collapse_walkthrough: false
#   auto_review:
#     enabled: true
#     drafts: false
# chat:
#   auto_reply: true
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
