# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request: # Ensure this exists
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # ignore error
        with:
          debug: true
          review_simple_changes: false
          review_comment_lgtm: false
